<?php

use Phinx\Migration\AbstractMigration;

class CoutryStateInserts extends AbstractMigration
{

    public function up()
    {
        $this->execute("
            INSERT INTO `countries` (`id`, `name`) VALUES
                (98, 'Afeganistão'),
                (142, 'Albânia'),
                (159, 'Alemanha'),
                (143, 'Andorra'),
                (10, 'Angola'),
                (63, 'Antígua e Barbuda'),
                (130, 'Arábia Saudita'),
                (86, 'Argentina'),
                (9, 'Argélia'),
                (144, 'Armênia'),
                (189, 'Austrália'),
                (146, 'Azerbaijão'),
                (53, 'África do Sul'),
                (145, 'Áustria'),
                (64, 'Bahamas'),
                (99, 'Bahrein'),
                (100, 'Bangladesh'),
                (65, 'Barbados'),
                (66, 'Belize'),
                (11, 'Benin'),
                (148, 'Bélgica'),
                (147, 'Bielorrúsia'),
                (87, 'Bolívia'),
                (12, 'Botsuana'),
                (149, 'Bósnia-Herzegovina'),
                (1, 'Brasil'),
                (102, 'Brunei'),
                (150, 'Bulgária'),
                (13, 'Burkina Faso'),
                (14, 'Burundi'),
                (101, 'Butão'),
                (16, 'Cabo Verde'),
                (15, 'Camarões'),
                (104, 'Camboja'),
                (83, 'Canadá'),
                (128, 'Catar'),
                (114, 'Cazaquistão'),
                (18, 'Chade'),
                (89, 'Chile'),
                (105, 'China'),
                (152, 'Chipre'),
                (90, 'Colômbia'),
                (20, 'Congo'),
                (115, 'Coreia do Norte'),
                (116, 'Coreia do Sul'),
                (32, 'Costa do Marfim'),
                (67, 'Costa Rica'),
                (151, 'Croácia'),
                (68, 'Cuba'),
                (154, 'Dinamarca'),
                (22, 'Djibuti'),
                (69, 'Dominica'),
                (23, 'Egito'),
                (71, 'El Salvador'),
                (138, 'Emirados Árabes Unidos'),
                (91, 'Equador'),
                (25, 'Eritreia'),
                (181, 'Eslováquia'),
                (182, 'Eslovênia'),
                (183, 'Espanha'),
                (85, 'Estados Unidos'),
                (155, 'Estônia'),
                (26, 'Etiópia'),
                (190, 'Fiji'),
                (127, 'Filipinas'),
                (156, 'Finlândia'),
                (157, 'França'),
                (27, 'Gabão'),
                (29, 'Gana'),
                (28, 'Gâmbia'),
                (158, 'Geórgia'),
                (72, 'Granada'),
                (160, 'Grécia'),
                (73, 'Guatemala'),
                (92, 'Guiana'),
                (30, 'Guiné'),
                (24, 'Guiné Equatorial'),
                (31, 'Guiné-Bissau'),
                (74, 'Haiti'),
                (174, 'Holanda'),
                (75, 'Honduras'),
                (161, 'Hungria'),
                (141, 'Iêmen'),
                (19, 'Ilhas Comores'),
                (122, 'Ilhas Maldivas'),
                (192, 'Ilhas Marshall'),
                (41, 'Ilhas Mauricio'),
                (199, 'Ilhas Salomão'),
                (50, 'Ilhas Seychelles'),
                (108, 'Indonésia'),
                (110, 'Iraque'),
                (109, 'Irã'),
                (163, 'Irlanda'),
                (162, 'Islândia'),
                (111, 'Israel'),
                (164, 'Itália'),
                (107, 'Índia'),
                (76, 'Jamaica'),
                (112, 'Japão'),
                (113, 'Jordânia'),
                (191, 'Kiribati'),
                (117, 'Kuwait'),
                (119, 'Laos'),
                (34, 'Lesoto'),
                (165, 'Letônia'),
                (35, 'Libéria'),
                (166, 'Liechtenstein'),
                (167, 'Lituânia'),
                (120, 'Líbano'),
                (36, 'Líbia'),
                (168, 'Luxemburgo'),
                (169, 'Macedônia'),
                (37, 'Madagascar'),
                (38, 'Malawi'),
                (121, 'Malásia'),
                (39, 'Mali'),
                (170, 'Malta'),
                (42, 'Marrocos'),
                (40, 'Mauritânia'),
                (84, 'México'),
                (193, 'Micronésia'),
                (43, 'Moçambique'),
                (171, 'Moldávia'),
                (123, 'Mongólia'),
                (173, 'Montenegro'),
                (172, 'Mônaco'),
                (103, 'Myanmar'),
                (44, 'Namíbia'),
                (194, 'Nauru'),
                (124, 'Nepal'),
                (77, 'Nicarágua'),
                (46, 'Nigéria'),
                (45, 'Níger'),
                (175, 'Noruega'),
                (195, 'Nova Zelândia'),
                (125, 'Omã'),
                (196, 'Palau'),
                (78, 'Panamá'),
                (197, 'Papua Nova Guiné'),
                (126, 'Paquistão'),
                (93, 'Paraguai'),
                (94, 'Peru'),
                (176, 'Polônia'),
                (177, 'Portugal'),
                (33, 'Quênia'),
                (118, 'Quirguistão'),
                (187, 'Reino Unido'),
                (17, 'República Centro-Africana'),
                (21, 'República Democrática do Congo'),
                (70, 'República Dominicana'),
                (153, 'República Tcheca'),
                (178, 'Romênia'),
                (47, 'Ruanda'),
                (129, 'Rússia'),
                (198, 'Samoa'),
                (179, 'San Marino'),
                (80, 'Santa Lúcia'),
                (79, 'São Cristóvão e Nevis'),
                (48, 'São Tomé e Príncipe'),
                (81, 'São Vicente e Granadinas'),
                (49, 'Senegal'),
                (51, 'Serra Leoa'),
                (180, 'Sérvia'),
                (131, 'Singapura'),
                (133, 'Síria'),
                (52, 'Somália'),
                (132, 'Sri Lanka'),
                (56, 'Suazilândia'),
                (55, 'Sudão'),
                (54, 'Sudão do Sul'),
                (184, 'Suécia'),
                (185, 'Suíça'),
                (95, 'Suriname'),
                (134, 'Tadjiquistão'),
                (135, 'Tailândia'),
                (57, 'Tanzânia'),
                (106, 'Timor Leste'),
                (58, 'Togo'),
                (200, 'Tonga'),
                (82, 'Trinidad e Tobago'),
                (59, 'Tunísia'),
                (137, 'Turcomenistão'),
                (136, 'Turquia'),
                (201, 'Tuvalu'),
                (186, 'Ucrânia'),
                (60, 'Uganda'),
                (96, 'Uruguai'),
                (139, 'Uzbequistão'),
                (202, 'Vanuatu'),
                (188, 'Vaticano'),
                (97, 'Venezuela'),
                (140, 'Vietnã'),
                (61, 'Zâmbia'),
                (62, 'Zimbábue');
	        ");


        $this->execute("INSERT INTO `states` (`id`, `name`, `statecode`, `country_id`) VALUES
                            (1, 'Acre', 'AC', 1),
                            (2, 'Alagoas', 'AL', 1),
                            (3, 'Amazonas', 'AM', 1),
                            (4, 'Amapá', 'AP', 1),
                            (5, 'Bahia', 'BA', 1),
                            (6, 'Ceará', 'CE', 1),
                            (7, 'Distrito Federal', 'DF', 1),
                            (8, 'Espírito Santo', 'ES', 1),
                            (9, 'Goiás', 'GO', 1),
                            (10, 'Maranhão', 'MA', 1),
                            (11, 'Minas Gerais', 'MG', 1),
                            (12, 'Mato Grosso do Sul', 'MS', 1),
                            (13, 'Mato Grosso', 'MT', 1),
                            (14, 'Pará', 'PA', 1),
                            (15, 'Paraíba', 'PB', 1),
                            (16, 'Pernambuco', 'PE', 1),
                            (17, 'Piauí', 'PI', 1),
                            (18, 'Paraná', 'PR', 1),
                            (19, 'Rio de Janeiro', 'RJ', 1),
                            (20, 'Rio Grande do Norte', 'RN', 1),
                            (21, 'Rondônia', 'RO', 1),
                            (22, 'Roraima', 'RR', 1),
                            (23, 'Rio Grande do Sul', 'RS', 1),
                            (24, 'Santa Catarina', 'SC', 1),
                            (25, 'Sergipe', 'SE', 1),
                            (26, 'São Paulo', 'SP', 1),
                            (27, 'Tocantins', 'TO', 1);");
    }
}
